FROM golang:1.19

# RUN apk add --no-cache git

RUN mkdir /app
ADD . /app
WORKDIR /app 

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN go build -o /banking_app

EXPOSE 8088

# CMD [ "sleep", "1000000000000000" ]
# CMD [ "go", "run", "main.go" ]
CMD [ "/banking_app" ]