version: '3'

services:
  banking_app_golang:
    build:
      context: .
      dockerfile: Dockerfile-golang
    container_name: banking_app_golang
    working_dir: /app
    volumes:
      - ./:/app
  banking_app_service:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: banking_app_service
    working_dir: /app
    ports:
      - "8088:80"
    volumes:
      - ./:/app
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
networks:
  default:
    external:
      name: local_network
