version: '3'

services:
  banking_app_golang:
    build:
      context: .
      dockerfile: Dockerfile-golang
    container_name: banking_app_golang
    working_dir: /app
    volumes:
      - ./:/app

  postgres:
    container_name: postgres
    image: registry.alo-dev.com/dockerhub/library/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=root
networks:
  default:
    external:
      name: local_network
